pub mod annotation;
pub mod assistant;
pub mod assistant_proposal;
pub mod assistant_routing;
pub mod conversation;
pub mod embedding;
pub mod embedding_resources;
pub mod entry;
pub mod export;
pub mod job;
mod llm_http;
pub mod note_catalog;
pub mod pdf_reader;
pub mod pdf_text;
pub mod pdf_parse_queue;
#[cfg(test)]
mod pdf_parse_queue_tests;
pub mod browser;
mod browser_isolation;
pub mod research;
pub mod sciverse;
pub mod search;
pub mod settings;
pub mod tag;
pub mod tag_note;
pub mod tag_reading;
#[cfg(test)]
mod tag_tests;
pub mod translation;
pub mod workspace;
