const repo = 'https://github.com/SugrSertraline/neuink';
const portableDownload = 'https://cdn.sugrsertraline.top/Neuink-windows-x64-portable.zip';
const sourceRef = (process.env.GUIDE_SOURCE_REF || 'main').split('/').map(encodeURIComponent).join('/');
const esc = s => String(s).replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
export function shell({ page, pages, content, toc = [], neighbors = {}, siteUrl, absoluteAssets = false }) {
  const base = absoluteAssets ? siteUrl : '';
  const title = page ? `${page.title} · Neuink 使用手册` : 'Neuink · 让每一次阅读，都留下可追溯的理解';
  const description = page?.description ?? '本地优先的文献阅读与知识工作台。完整了解资料库、PDF、双语翻译、证据笔记、AI 研究和成果分享。';
  const nav = [...new Set(pages.map(p => p.group))].map(group => `<div class="nav-group"><p>${group}</p>${pages.filter(p => p.group === group).map(p => `<a href="${base}${p.id}.html" ${page?.id === p.id ? 'aria-current="page"' : ''}>${p.title}</a>`).join('')}</div>`).join('');
  return `<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="color-scheme" content="light dark"><title>${esc(title)}</title><meta name="description" content="${esc(description)}"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:type" content="website"><link rel="canonical" href="${siteUrl}${page ? `${page.id}.html` : ''}"><link rel="icon" href="${base}assets/logo.png"><link rel="stylesheet" href="${base}assets/style.css"><script src="${base}assets/app.js" defer></script></head>
<body class="${page ? 'guide-page' : 'home-page'}"><a class="skip" href="#main">跳到正文</a>
<header class="site-header">${page ? '<button class="menu-button" type="button" aria-expanded="false" aria-controls="guide-nav" hidden>目录</button>' : ''}<a class="brand" href="${base}index.html"><img src="${base}assets/logo.png" width="36" height="36" alt=""><span>Neuink<small>文献阅读 · 知识工作台</small></span></a><nav class="top-nav" aria-label="主导航"><a href="${base}index.html#features">功能全览</a><a class="nav-reading" href="${base}start.html">开始阅读</a><a href="${portableDownload}">下载 Windows 便携版</a><a href="https://sugrsertraline.github.io/homepage/">作者主页</a><a href="${repo}">GitHub ↗</a></nav><div class="header-actions"><button class="search-trigger" type="button" data-search-open hidden>搜索手册 <kbd>⌘ / Ctrl K</kbd></button><button class="theme-button" type="button" aria-label="切换深浅主题" hidden>深色</button></div></header>
${page ? `<div class="guide-layout"><aside class="guide-nav" id="guide-nav" aria-label="手册目录"><a class="overview-link" href="${base}index.html">← 功能全览</a>${nav}<a class="nav-source" href="${repo}/blob/main/docs/development/dev-plan.md">开发状态与版本边界 ↗</a></aside><main id="main" class="doc" tabindex="-1">${content}<nav class="page-neighbors" aria-label="相邻章节">${neighbors.prev ? `<a href="${neighbors.prev.id}.html"><small>上一章</small>${neighbors.prev.title} ←</a>` : '<span></span>'}${neighbors.next ? `<a href="${neighbors.next.id}.html"><small>下一章</small>${neighbors.next.title} →</a>` : '<a href="index.html">回到功能全览 →</a>'}</nav><p class="doc-source">按当前实现整理 · <a href="${repo}/blob/${sourceRef}/website/content/${page.id}.md">查看本页源文档</a> · <a href="${repo}/issues">反馈说明问题</a></p></main><aside class="toc" aria-label="本页目录"><p>本页内容</p>${toc.map(t => `<a href="#${t.id}">${esc(t.label)}</a>`).join('')}</aside></div>` : `<main id="main" tabindex="-1">${content}</main>`}
<footer class="site-footer"><a class="footer-brand" href="${base}index.html">Neuink</a><p>资料留在本地，理解连接证据。</p><nav aria-label="页脚导航"><a href="${base}data.html">数据与隐私</a><a href="${base}faq.html">常见问题</a><a href="${repo}/blob/main/LICENSE">Apache-2.0</a><a href="${repo}">源代码 ↗</a></nav></footer>
<dialog class="search-dialog" aria-labelledby="search-heading"><div class="search-head"><h2 id="search-heading">搜索功能与使用方法</h2><button type="button" data-search-close aria-label="关闭搜索">关闭 <kbd>Esc</kbd></button></div><label class="sr-only" for="guide-search">搜索词</label><input id="guide-search" type="search" placeholder="试试：标签笔记、翻译、导出、模型…" autocomplete="off"><p class="search-status" role="status" aria-live="polite">输入功能名称或遇到的问题。</p><div class="search-results"></div><p class="search-hint">搜索只在本机完成，不上传查询内容。按 Tab 选择结果，Enter 打开。</p></dialog>
</body></html>`;
}

export function home(pages) {
  const groups = [...new Set(pages.map(p => p.group))];
  return `<section class="hero section"><div class="hero-copy"><p class="eyebrow">LOCAL FIRST · SOURCE GROUNDED</p><h1>读过的文献，<br>成为有据可循的<span>理解。</span></h1><p class="hero-intro">从 PDF 的一段原文，到跨篇研究的一个结论。<br>Neuink 把阅读、笔记、证据与 AI 放在同一张工作台上。</p><div class="hero-actions"><a class="button primary" href="start.html">开始使用 <span>↗</span></a><a class="button secondary" href="#features">探索全部功能 ↓</a></div><p class="hero-note">本地资料库 · 你选择的模型 · 可审阅的 AI 修改</p></div>
<div class="evidence-visual" aria-label="从原文到笔记再回到来源的流程示意"><div class="visual-top"><span class="live-dot"></span> 一条可以回溯的思考路径 <span>示意</span></div><div class="visual-paper"><div class="paper-label">01 / 阅读原文</div><h2>研究问题，不止于摘要。</h2><p class="sample-lines">把论证放回上下文，核对方法与结果。<br><mark>重要的结论，始终保留它的出处。</mark><br>原始版式、结构化片段、双语阅读。</p><div class="source-pill">原文片段 <span>→</span> 来源快照</div></div><div class="visual-note"><div class="paper-label">02 / 形成自己的笔记</div><h3>理解与证据，一起留下。</h3><ul><li>记录结论与适用条件</li><li>保留矛盾与未核对项</li><li>点击来源，回到原文 <span class="citation">来源 ↗</span></li></ul></div><div class="visual-bottom"><span>PDF / Reflow</span><span>Source Link</span><span>Markdown / DOCX</span></div></div></section>
<section class="section screenshot-showcase" aria-labelledby="screenshots-heading"><p class="eyebrow">实机界面 · 点击图片放大</p><h2 id="screenshots-heading">先看工作台，<br>再开始你的第一篇笔记。</h2><figure class="product-shot"><a href="assets/screenshots/pdf-note-workspace.png" aria-label="打开原尺寸：PDF 与笔记分屏截图"><img src="assets/screenshots/pdf-note-workspace.png" width="2378" height="1489" loading="lazy" decoding="async" alt="Neuink 实机截图：左侧 PDF 原文，右侧带公式与来源链接的演示笔记"></a><figcaption><strong>左边核对原文，右边整理理解。</strong> 顶部标签管理阅读对象，右侧蓝色来源链接让笔记返回证据。从原文到笔记，在同一工作区完成阅读与整理。</figcaption></figure><a class="text-link" href="screenshots.html">了解系统概念与图文使用教程 →</a></section>
<div class="workflow-strip"><a href="import.html"><b>01</b> 收集整理</a><span>→</span><a href="pdf.html"><b>02</b> 阅读对照</a><span>→</span><a href="sources.html"><b>03</b> 连接证据</a><span>→</span><a href="assistant.html"><b>04</b> 检索研究</a><span>→</span><a href="export.html"><b>05</b> 导出分享</a></div>
<section class="section narrative" id="experience"><div class="section-heading"><p class="eyebrow">一张工作台，贯穿研究过程</p><h2>让功能服务于<br>你正在思考的问题。</h2></div><div class="experience-tabs" role="tablist" aria-label="探索工作方式"><button role="tab" id="tab-reading" aria-controls="panel-reading" aria-selected="true" data-panel="reading">阅读与对照</button><button role="tab" id="tab-evidence" aria-controls="panel-evidence" aria-selected="false" tabindex="-1" data-panel="evidence">笔记与证据</button><button role="tab" id="tab-research" aria-controls="panel-research" aria-selected="false" tabindex="-1" data-panel="research">AI 与研究</button></div>
<div class="experience-panel" id="panel-reading" role="tabpanel" aria-labelledby="tab-reading" tabindex="0"><div><span class="chapter-number">01 — READ</span><h3>原文不离手，<br>多篇不失序。</h3><p>保留 PDF 排版，也能用重排视图连续阅读。把两篇论文放在左右两侧，让原文、译文和主题笔记各得其所。</p><a class="text-link" href="parallel.html">了解标签平行阅读 →</a></div><dl class="feature-rows"><div><dt>原始 PDF</dt><dd>连续／书页、单页／双页、片段预览与收藏位置</dd></div><div><dt>重排与双语</dt><dd>段落、表格、公式、图片，以及可暂停的全文翻译</dd></div><div><dt>主题阅读</dt><dd>同标签论文列表，独立阅读位置，多标签与分屏</dd></div></dl></div>
<div class="experience-panel" id="panel-evidence" role="tabpanel" aria-labelledby="tab-evidence" tabindex="0" hidden><div><span class="chapter-number">02 — CONNECT</span><h3>写下结论，<br>也留下来路。</h3><p>从某一段的疑问到一个主题的综合笔记，来源链接保留原文快照；关系图呈现你已经建立的真实关联。</p><a class="text-link" href="sources.html">了解来源与反向引用 →</a></div><dl class="feature-rows"><div><dt>不同尺度的记录</dt><dd>文档笔记、标签综合笔记、片段笔记与批注</dd></div><div><dt>可追溯来源</dt><dd>预览快照、定位原文、查看反向引用与失效提示</dd></div><div><dt>带得走的成果</dt><dd>Word、TXT、Markdown 资料包与选择性导出</dd></div></dl></div>
<div class="experience-panel" id="panel-research" role="tabpanel" aria-labelledby="tab-research" tabindex="0" hidden><div><span class="chapter-number">03 — INVESTIGATE</span><h3>让助手参与，<br>让你掌握范围。</h3><p>选择上下文，核对检索结果，审阅每一次修改。模型和服务由你配置，保存到本地的成果由你管理。</p><a class="text-link" href="assistant.html">了解 AI 助手与审阅 →</a></div><dl class="feature-rows"><div><dt>本地与在线检索</dt><dd>关键词／语义／混合搜索，公开论文与网页发现</dd></div><div><dt>阅读更多材料</dt><dd>内嵌网页、公开 PDF 文字与可用视频字幕</dd></div><div><dt>修改先审阅</dt><dd>查看提案、核对来源，确认后才应用到目标文件</dd></div></dl></div></section>
<section class="directory-section" id="features"><div class="section directory"><div class="directory-heading"><div><p class="eyebrow">完整功能手册</p><h2>每一个功能，<br>都有具体的用法。</h2></div><p>从入口到操作，从结果到边界。<br>${pages.length} 篇专题指南，按你的任务逐步阅读。</p></div><div class="directory-grid">${groups.map((group, i) => `<section class="directory-group"><h3><span>0${i + 1}</span>${group}</h3>${pages.filter(p => p.group === group).map(p => `<a href="${p.id}.html"><strong>${p.title}<span>↗</span></strong><p>${p.description}</p></a>`).join('')}</section>`).join('')}</div></div></section>
<section class="section principles"><div><p class="eyebrow">数据与选择权</p><h2>本地优先，<br>边界清楚。</h2><a class="text-link" href="data.html">了解数据与联网范围 →</a></div><div class="principle-list"><article><span>01</span><div><h3>资料是普通本地文件</h3><p>PDF、笔记、译文与会话保存在 Workspace。搜索缓存可以重建，迁移会保留原目录。</p></div></article><article><span>02</span><div><h3>模型与服务按需连接</h3><p>基础阅读、笔记与关键词检索无需 LLM。AI 和远程解析会把相应材料交给你配置的服务。</p></div></article><article><span>03</span><div><h3>明确已经支持什么</h3><p>关系图展示已记录的关系；视频读取只覆盖简介与可用字幕；规划功能不会混入已实现介绍。</p></div></article></div></section>
<section class="section closing"><p class="eyebrow">从一篇论文开始</p><h2>把下一次阅读，<br>变成可继续的研究。</h2><div class="hero-actions"><a class="button primary" href="start.html">阅读入门指南 ↗</a><a class="button secondary" href="${portableDownload}">下载 Windows 便携版</a></div><p>产品持续迭代中。各平台可用性、构建与验收状态请以发布说明为准。</p></section>`;
}
