/** Short in-place instruction and observable result for every tutorial step. */
export const GUIDE_ACTIONS: Record<string, { action: string; result: string }> = {
  welcome: { action:'将鼠标移到说明或左侧图标上；也可用 Tab 逐项聚焦说明。', result:'对应入口会在原界面描边并显示名称。' },
  'open-pdf': { action:'观察右侧已自动打开的演示 PDF，无需重新导入。', result:'正文所在的阅读区域被聚焦；继续后再认识各个入口。' },
  'nav-library': { action:'观察左侧条目库和相邻内容，本步不切换或收起侧栏。', result:'侧栏保持展开，说明与界面位置一一对应。' },
  'nav-details': { action:'对照高亮的条目详情入口和相邻内容面板，查看阅读入口与笔记分组。', result:'详情侧栏已展示演示论文，可从这里打开 PDF、重排或笔记。' },
  'nav-search': { action:'观察高亮的搜索入口；本步不要求输入关键词。', result:'左侧自动切到搜索面板；之后可在这里寻找论文与笔记。' },
  'nav-assistant': { action:'观察助手入口，本步不用发送问题。', result:'左侧切到对话，右侧演示 PDF 继续保留。' },
  'nav-tags': { action:'观察高亮的标签阅读入口；本步不要求选择标签。', result:'侧栏切到按标签组织的阅读面板；空范围会显示空状态。' },
  'nav-settings': { action:'观察设置入口；以后可从“资料库与数据”回放教程。', result:'设置作为阅读标签打开，不会替换资料库数据。' },
  'parse-choices': { action:'可点击高亮的“查看客户端导入图文教程”，或直接继续。', result:'教程会在新标签打开，并进入下一步的截图说明。' },
  'parse-zip': { action:'依次看下载、打包和导入截图；需要时点击“复制链接”。', result:'复制成功会有提示；本步不会上传或解析你的 PDF。' },
  'parse-service': { action:'可选：填写 MinerU URL；服务需要密钥时再填写下方 API Key。', result:'配置保留在解析设置中，不会自动调用聊天模型。' },
  parsed: { action:'观察页面中自动描出的真实解析块，无需再次提交解析。', result:'描边对应演示论文已有的块和页内位置。' },
  blocks: { action:'观察自动描边的段落，本步固定页面位置。', result:'描边与真实内容块重合，不会因滚动或误点击移走。' },
  hover: { action:'观察自动弹出的片段预览；也可悬停其他正文块。', result:'预览显示这篇论文真实的原文、已有译文或记录。' },
  reflow: { action:'观察自动打开的重排页，再与之前的 PDF 排版比较。', result:'内容按解析块重排，原 PDF 文件不被改写。' },
  'translation-model': { action:'有模型连接时，在高亮位置选择“阅读翻译模型”。', result:'翻译任务之后使用该连接；本步不会发出翻译请求。' },
  'translation-task': { action:'可直接完成并继续；若想了解任务面板，点击“翻译任务”（窄工具栏先点“更多 PDF 操作”）。', result:'打开面板只供查看，关闭后仍回到本步；不会自动开始翻译。' },
  'translation-view': { action:'可点击高亮的“译文”观察覆盖效果；想恢复时点击旁边“原文”。', result:'切换后，有译文的正文在原 PDF 位置显示译文，未翻译区域有提示。' },
  'selection-translation': { action:'观察系统模拟选字；实际拖选可在后面的批注步骤练习。', result:'自动展示选区与工具条，不改变真实选区、不调用翻译模型。' },
  split: { action:'可右键高亮的 PDF 标签选择“复制到另一分栏”，或直接继续。', result:'手动复制后会出现两个独立阅读视图；若直接继续，下一步会自动准备。' },
  'split-translation': { action:'左侧保持“原文”，在右侧工具栏点击高亮的“译文”。', result:'左右视图分别显示原文和译文，滚动定位可联动。' },
  'split-note': { action:'在左侧文档笔记行末点击“在 PDF 旁打开”。', result:'工作区一边保留 PDF，另一边打开同一条目的笔记。' },
  'note-types': { action:'依次悬停本步三条说明，对照左侧片段记录与文档笔记入口。', result:'说明与相应的真实界面位置同步标注；此步不创建记录。' },
  'segment-note': { action:'可右键高亮的 PDF 段落，选择“编辑片段笔记（浮窗）”。', result:'打开后可练习记录；不输入或保存也能继续教程。' },
  annotation: { action:'可在高亮的 PDF 正文中拖选文字，再点选区工具条的“批注”。', result:'选择后会打开批注编辑器；保存前不会改变原文。' },
  'document-note': { action:'演示论文已有笔记；想练习时点击左侧“新建文档笔记”。', result:'实际点击后才创建“未命名笔记”；直接继续不会新增文件。' },
  'write-note': { action:'系统已打开演示笔记；可输入自己的理解，再按 Ctrl/Cmd + S。', result:'只有实际保存成功才算写入；直接继续不会改写笔记。' },
  'source-note': { action:'确认系统已并排打开 PDF 和笔记，再右键高亮原文块选择插入来源。', result:'来源组件出现在笔记正文中，点击可返回对应片段。' },
  'assistant-model': { action:'需要真实问答时，点击“新增配置”，填写自己的模型连接并指定助手模型。', result:'连接配置完成后才能实际调用；本步不会产生模型费用。' },
  'assistant-context': { action:'先核对默认跟随的阅读对象；如需固定，可点“选择元素”或输入 @。', result:'明确选择后，本次发送范围显示在输入区；不选择也能继续。' },
  'assistant-send': { action:'有模型时可输入示例问题，核对对象后点击“发送”；也可直接继续。', result:'只有实际发送才会调用模型；发送不等于回答已经成功。' },
  'assistant-proposal': { action:'在输入区提出整理要求，并明确指定目标笔记。', result:'若助手生成修改提案，还需在审阅页检查差异并确认后才会写入。' },
  tags: { action:'可点“生成推荐标签”，勾选合适的中文标签后再点击添加。', result:'只有确认添加后条目标签才改变；不合适的建议可以不选。' },
  finish: { action:'查看任务目录中已完成与已跳过的步骤，然后点击“结束引导”。', result:'教程关闭；示例论文和你的阅读记录继续保留。' },
};
