import type {
  AssistantContextSnapshot,
  ConversationSourceLink,
  ScopeSnapshot
} from '@/shared/ipc/assistantApi';
import { readNote, readPdfReader } from '@/shared/ipc/workspaceApi';
import type {
  AssistantActiveNote,
  AssistantNoteProposal,
  AssistantTaskPlan
} from '@/shared/types/assistant';
import { requestAssistantClarification } from '../runtime/clarification';

export async function resolveTargetNote({
  contextSnapshot,
  currentNote,
  plan,
  root
}: {
  contextSnapshot: AssistantContextSnapshot;
  currentNote?: AssistantActiveNote | null;
  plan: AssistantTaskPlan;
  root: string;
}) {
  if (plan.target.kind === 'segment_note') {
    const entryId = plan.target.entryId;
    const segmentUid = plan.target.segmentUid;
    if (!entryId || !segmentUid) {
      requestAssistantClarification('target_segment', '请选择一个要创建或修改片段笔记的 PDF 片段。');
    }
    const reader = await readPdfReader(root, entryId);
    const markdown = reader.segment_notes.find(
      (note) => note.segment_uid === segmentUid
    )?.text ?? '';
    return { markdown, note: null };
  }
  if (plan.intent !== 'note_update') return { markdown: '', note: null };
  const entryId = plan.target.entryId;
  const noteId = plan.target.noteId;
  if (!entryId || !noteId) {
    requestAssistantClarification(
      'active_note',
      '请用 @ 指定一个要修改的 Markdown 笔记；如果有重名，请选择具体的完整名称。'
    );
  }
  if (contextSnapshot.active_note?.note_id === noteId && !contextSnapshot.active_note.truncated) {
    return {
      markdown: contextSnapshot.active_note.markdown,
      note: {
        entryId,
        entryTitle: contextSnapshot.active_note.entry_title,
        noteId,
        noteTitle: contextSnapshot.active_note.note_title
      }
    };
  }
  const document = await readNote(root, entryId, noteId);
  return {
    markdown: document.markdown,
    note: {
      entryId,
      entryTitle: targetEntryTitle(entryId, contextSnapshot, currentNote),
      noteId,
      noteTitle: document.title
    }
  };
}

export function buildDraftProposal({
  beforeMarkdown,
  contextSnapshot,
  currentEntry,
  currentNote,
  evidenceSources,
  markdown,
  operation,
  plan,
  scope
}: {
  beforeMarkdown: string;
  contextSnapshot: AssistantContextSnapshot;
  currentEntry?: { id: string; title: string } | null;
  currentNote?: AssistantActiveNote | null;
  evidenceSources: ConversationSourceLink[];
  markdown: string;
  operation: 'append' | 'create' | 'delete' | 'patch' | 'prepend' | 'replace';
  plan: AssistantTaskPlan;
  scope: ScopeSnapshot;
}): AssistantNoteProposal {
  const entryId = plan.target.entryId ?? currentNote?.entryId ?? currentEntry?.id ?? scope.entry_ids[0];
  if (!entryId) {
    requestAssistantClarification(
      'active_entry',
      '你希望把新笔记保存在哪个 Entry 下？请用 @ 指定一个 Entry 或 PDF。'
    );
  }
  const entryTitle = currentNote?.entryId === entryId
    ? currentNote.entryTitle
    : currentEntry?.id === entryId
      ? currentEntry.title
      : scope.entry_titles[scope.entry_ids.indexOf(entryId)] ?? entryId;
  const effectiveOperation = operation === 'patch' && !beforeMarkdown ? 'replace' : operation;
  const noteId = effectiveOperation === 'create'
    ? null
    : plan.target.noteId ?? currentNote?.noteId ?? null;
  if (effectiveOperation !== 'create' && !noteId && plan.target.kind !== 'segment_note') {
    requestAssistantClarification(
      'active_note',
      '请用 @ 指定要追加、替换或完善的具体 Markdown 笔记。'
    );
  }
  const after = effectiveOperation === 'append'
    ? `${beforeMarkdown.trimEnd()}\n\n${markdown}`.trim()
    : effectiveOperation === 'prepend'
      ? `${markdown}\n\n${beforeMarkdown.trimStart()}`.trim()
    : markdown;

  return {
    action: effectiveOperation,
    afterMarkdown: after,
    beforeMarkdown: effectiveOperation === 'create' ? '' : beforeMarkdown,
    createdAt: new Date().toISOString(),
    entryId,
    entryTitle,
    id: `note-proposal-${Date.now()}-${Math.random().toString(36).slice(2)}`,
    markdown,
    noteId,
    noteTitle: currentNote?.noteTitle ?? null,
    pageIdx: contextSnapshot.pinned_segments[0]?.page_idx ?? null,
    patchOperations: effectiveOperation === 'patch' || effectiveOperation === 'delete'
      ? [{ newText: markdown, oldText: beforeMarkdown, type: 'replace_exact' }]
      : undefined,
    rationale: 'Generated by the dedicated Note Writer from the frozen task context.',
    segmentUid: plan.target.kind === 'segment_note' ? plan.target.segmentUid ?? null : null,
    sources: citedEvidenceSources(markdown, evidenceSources).map(({ source, marker }) => ({
      entryId: source.entry_id,
      entryTitle: source.entry_title,
      marker: `S${marker}`,
      pageIdx: source.page_idx,
      quote: source.quote,
      segmentUid: source.segment_uid
    })),
    status: 'pending',
    targetKind: plan.target.kind === 'segment_note' ? 'segment_note' : 'markdown_note',
    title: currentNote?.noteTitle ?? `${entryTitle} 笔记`
  };
}

export function citedEvidenceSources(markdown: string, sources: ConversationSourceLink[]) {
  const markers = [...markdown.matchAll(/\[S(\d+)]/g)]
    .map((match) => Number(match[1]))
    .filter((marker, index, items) => marker > 0 && items.indexOf(marker) === index);
  return markers.flatMap((marker) => {
    const source = sources[marker - 1];
    return source ? [{ marker, source }] : [];
  });
}

function targetEntryTitle(
  entryId: string,
  contextSnapshot: AssistantContextSnapshot,
  currentNote?: AssistantActiveNote | null
) {
  if (contextSnapshot.active_entry?.entry_id === entryId) {
    return contextSnapshot.active_entry.entry_title;
  }
  if (currentNote?.entryId === entryId) return currentNote.entryTitle;
  return entryId;
}
